"""Derive a reversible color/shape theme from lesson styles, without editing their layout.
Run again after adding module styles; hand-tuned design lives in research-theme.css.
"""
from pathlib import Path
import colorsys, re
import tinycss2
ROOT = Path(__file__).resolve().parent.parent
sources = re.findall(r'href="([^"]+\.css)"', (ROOT/'index.template.html').read_text())

def recolor(match):
    s=match.group()[1:]
    if len(s) in (3,4): s=''.join(c*2 for c in s)
    rgb=[int(s[i:i+2],16)/255 for i in (0,2,4)]
    h,l,sat=colorsys.rgb_to_hls(*rgb)
    if not 145 <= h*360 <= 275 or sat < .08: return match.group()
    if l < .27:
        v=round(255*(.065+l*.55)); out=[v,v,v]
    elif l < .48:
        v=round(l*255); out=[v,v,v-2]
    elif sat > .48 and l < .83:
        out=[241,204,103]
    else:
        v=min(245,round(l*255)); out=[v,v,max(0,v-3)]
    return '#'+''.join(f'{v:02x}' for v in out)+s[6:]

HEX=re.compile(r'#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{4}\b|#[0-9a-fA-F]{3}\b')
def rules(text):
    out=[]
    for rule in tinycss2.parse_stylesheet(text, skip_comments=True, skip_whitespace=True):
        if rule.type=='at-rule' and rule.content is not None and rule.lower_at_keyword in ('media','supports'):
            inner=rules(tinycss2.serialize(rule.content))
            if inner: out.append('@'+rule.at_keyword+' '+tinycss2.serialize(rule.prelude)+'{'+inner+'}')
        elif rule.type=='qualified-rule':
            selector=tinycss2.serialize(rule.prelude)
            declarations=[]
            for d in tinycss2.parse_declaration_list(rule.content,skip_comments=True,skip_whitespace=True):
                if d.type!='declaration': continue
                value=tinycss2.serialize(d.value)
                new=HEX.sub(recolor,value)
                if d.name=='border-radius' and not ('50%' in value or '999' in value):
                    new='4px' if value.strip()!='0' else value
                if 'linear-gradient' in new and 'production-approved' not in selector:
                    new='var(--panel)'
                if new!=value: declarations.append(d.name+':'+new+('!important' if d.important else '')+';')
            if declarations: out.append(selector+'{'+''.join(declarations)+'}')
    return '\n'.join(out)
result=['/* Generated by scripts/build_dark_theme.py. Original lesson styles remain untouched. */']
for source in sources:
    if source in ('research-palette.css','research-theme.css'): continue
    result.extend(['/* '+source+' */',rules((ROOT/source).read_text())])
(ROOT/'research-palette.css').write_text('\n'.join(result)+'\n')
print('Built charcoal palette for',len(sources)-sum(s.startswith('research-') for s in sources),'stylesheets')
